DOITOEMApi/DOITOEMApi/Models/MstRegisterData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DOITOEMApi.Models
{
    public class MstRegisterData
    {
        public string registerId { get; set; }
        public string machineLineId { get; set; }
        public string PlcRegId { get; set; }
        public string PCat { get; set; }
        public string PUoc { get; set; }
        public string stringValue { get; set; }
        public string iVal { get; set; }
        public string iUOC { get; set; }
        public string iLcl { get; set; }
        public string fVal { get; set; }
        public string fUOC { get; set; }
        public string fLcl { get; set; }

    }
}

DOITOEMApi/DOITOEMApi/Controllers/mstRegisterDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DOITOEMApi;
using DOITOEMApi.Models;

namespace DOITOEMApi.Controllers
{
    public class mstRegisterDatasController : Controller
    {
        private IoT_dataEntities db = new IoT_dataEntities();

        // GET: mstRegisterDatas
        public ActionResult Index()
        {
            return View(db.mstRegisterDatas.ToList());
        }

        // GET: mstRegisterDatas/Details/5
        public ActionResult Details(int? id)
        {
            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            //mstRegisterData mstRegisterData = db.mstRegisterDatas.Find(id);
            //if (mstRegisterData == null)
            //{
            //    return HttpNotFound();
            //}
            return View();
        }

        // GET: mstRegisterDatas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: mstRegisterDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,PlcRegisterID,MachineLineID,RegisterProperties,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] mstRegisterData mstRegisterData)
        {
            if (ModelState.IsValid)
            {
                db.mstRegisterDatas.Add(mstRegisterData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(mstRegisterData);
        }

        // GET: mstRegisterDatas/Edit/5
       
        // POST: mstRegisterDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,PlcRegisterID,MachineLineID,RegisterProperties,CreatedDate,CreatedBy,ModifiedDate,ModifiedBy")] mstRegisterData mstRegisterData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(mstRegisterData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(mstRegisterData);
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult CallPartialView(string registerType)
        {
            string partialViewName = string.Empty;

            if (registerType == "1")
                partialViewName = "_StringRegisterData";
            else if (registerType == "2")
                partialViewName = "_IntRegiterData";
            else if (registerType == "3")
                partialViewName = "_FloatRegisterData";
            else if (registerType == "4")
                partialViewName = "_CodeRegisterData";
            else if (registerType == "5")
                partialViewName = "_BitRegisterData";

            return Json(partialViewName);
        }
        [HttpPost] 
        public JsonResult SaveDataStr(List<MstRegisterData> data)
        {
            var s = data;
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

DOITOEMApi/DOITOEMApi/Views/mstRegisterDatas/Create.cshtml
@model DOITOEMApi.mstRegisterData
@{
    ViewBag.Title = "Create";
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "Str",
        Value = "1"

    });
    listItems.Add(new SelectListItem
    {
        Text = "Int",
        Value = "2",
    }); ;
    listItems.Add(new SelectListItem
    {
        Text = "Float",
        Value = "3"

    });
    listItems.Add(new SelectListItem
    {
        Text = "Code",
        Value = "4"
    });
    listItems.Add(new SelectListItem
    {
        Text = "Bit",
        Value = "5"
    });
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Master Register Data</h4>
        <hr />
        <div class="form-group">

            <div class="col-md-10">
                <label>Register Id :</label>
                <input type="text" id="txtRegId" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                <label>MachineLine Id :</label>
                <input type="text" id="txtMachineLineId" />
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                <label>Plc Register Id :</label>
                <input type="text" id="txtPlcRegId" />
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                <label>Parameter Category :</label>
                <input type="text" id="txtPcat" />
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                <label>Parameter Unit :</label>
                <input type="text" id="txtPUoc" />
            </div>
        </div>

        <div class="form-group ">
            @Html.Label("RegsterType", htmlAttributes: new { @class = "control-label col-md-2" })
            @*@Html.DropDownListFor("RegsterType", new SelectList(Model._RegisterType, "RegisterType", "RegisterType"), "Select RegsterType", new { @style = "Width:100%", @class = "form-control select2", @id = "View_unit_code_excel", @onchange = "SelectUnitValuestream()" })*@
            @Html.DropDownListFor(Model => Model.RegParamType, listItems, "Select Parameter Type", new { @style = "Width:100%", @class = "form-control select2", @id = "View_unit_code_excel", @onchange = "SelectUnitValuestream()" })
        </div>
        <div class="form-group " id="parview1">
        </div>

        <div id="ParBitRegisterData" style="display:none">
            @Html.Partial("_BitRegisterData")
        </div>
        <div id="ParCodeRegisterData" style="display:none">
            @Html.Partial("_CodeRegisterData")
        </div>
        <div id="ParFloatRegisterData" style="display:none">
            @Html.Partial("_FloatRegisterData")
        </div>
        <div id="ParIntRegiterData" style="display:none">
            @Html.Partial("_IntRegiterData")
        </div>
        <div id="ParStringRegisterData" style="display:none">
            @Html.Partial("_StringRegisterData")
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" onclick="submitAndsaveData()" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
        var arrString = [];

function SelectUnitValuestream() {

        var uni_unit_code = $("#View_unit_code_excel").val();
                $.ajax({
                    url: '@Url.Action("CallPartialView","mstRegisterDatas")',
                    data: { registerType: uni_unit_code },
                    type: 'Post',
                    dataType: "json",
                    success: function (data) {
                        if (data == '_CodeRegisterData') {
                            hide();
                            $("#ParCodeRegisterData").css("display","block");

                        }
                        else if (data == '_BitRegisterData') {
                            hide();
                             $("#ParBitRegisterData").css("display","block");
                        }
                        else if (data == '_StringRegisterData') {
                            hide();
                             $("#ParStringRegisterData").css("display","block");
                        }
                        else if (data == '_IntRegiterData') {
                            hide();
                             $("#ParIntRegiterData").css("display","block");
                        }
                        else if (data == '_FloatRegisterData') {
                            hide();
                             $("#ParFloatRegisterData").css("display","block");
                        }
                        }
                        });
            }
            function hide() {
                $("#ParCodeRegisterData").css("display","none");
                $("#ParBitRegisterData").css("display", "none");
                $("#ParStringRegisterData").css("display", "none");
                $("#ParIntRegiterData").css("display", "none");
                $("#ParFloatRegisterData").css("display", "none");
            }


        function submitAndsaveData() {
            var registerId = $("#txtRegId").val();
            var machineLineId = $("#txtMachineLineId").val();
            var PlcRegId = $("#txtPlcRegId").val();
            var PCat = $("#txtPcat").val();
            var PUoc = $("#txtPUoc").val();

            var stringValue = $("#txt_string").val();

            var intIValue = $("#txt_intval").val();
            var intIUclValue = $("#txt_iucl").val();
            var intILclValue = $("#txt_ilcl").val();

            var fltValue = $("#txt_floatval").val();
            var fltUclValue = $("#txt_fucl").val();
            var fltLclValue = $("#txt_flcl").val();

            if (stringValue != "") {
                arrString.push({ registerId: registerId, machineLineId: machineLineId, PlcRegId: PlcRegId, PCat: PCat, PUoc: PUoc, stringValue: stringValue })
               
                $.ajax({
                    url: '@Url.Action("SaveDataStr","mstRegisterDatas")',
                    data: JSON.stringify(arrString),
                    type: "POST",
                    dataType: "json",
                    contentType: 'application/json;',
                    success: function (result) {

                    },
                });
            }
            if (intIValue != "") {
                 arrString.push({ registerId: registerId, machineLineId: machineLineId, PlcRegId: PlcRegId, PCat: PCat, PUoc: PUoc, iVal: intIValue, iUOC:intIUclValue ,iLcl:intILclValue})
               
                $.ajax({
                    url: '@Url.Action("SaveDataStr","mstRegisterDatas")',
                    data: JSON.stringify(arrString),
                    type: "POST",
                    dataType: "json",
                    contentType: 'application/json;',
                    success: function (result) {

                    },
                });
            }
            if (fltValue != "") {
                 arrString.push({ registerId: registerId, machineLineId: machineLineId, PlcRegId: PlcRegId, PCat: PCat, PUoc: PUoc, fVal: fltValue, fUOC:fltUclValue ,fLcl:fltLclValue})
               
                $.ajax({
                    url: '@Url.Action("SaveDataStr","mstRegisterDatas")',
                    data: JSON.stringify(arrString),
                    type: "POST",
                    dataType: "json",
                    contentType: 'application/json;',
                    success: function (result) {

                    },
                });
            }
        }
</script>

DOITOEMApi/DOITOEMApi/Views/mstRegisterDatas/Delete.cshtml
@model DOITOEMApi.mstRegisterData

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>mstRegisterData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlcRegisterID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlcRegisterID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MachineLineID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MachineLineID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterProperties)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterProperties)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DOITOEMApi/DOITOEMApi/Views/mstRegisterDatas/Details.cshtml
@model DOITOEMApi.mstRegisterData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>mstRegisterData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlcRegisterID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlcRegisterID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MachineLineID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MachineLineID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterProperties)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterProperties)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DOITOEMApi/DOITOEMApi/Views/mstRegisterDatas/Edit.cshtml
@model DOITOEMApi.mstRegisterData

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>mstRegisterData</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.PlcRegisterID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlcRegisterID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlcRegisterID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MachineLineID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MachineLineID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MachineLineID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegisterProperties, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegisterProperties, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegisterProperties, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DOITOEMApi/DOITOEMApi/Views/mstRegisterDatas/Index.cshtml
@model IEnumerable<DOITOEMApi.mstRegisterData>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlcRegisterID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MachineLineID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegisterProperties)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlcRegisterID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MachineLineID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegisterProperties)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>